version: '2'

services:
    db:
        image: mysql
        volumes:
                - ~/mysql:/var/lib/mysql
                - /etc/timezone:/etc/timezone:ro
                - /etc/localtime:/etc/localtime:ro
        ports:
                - 3306:3306
        environment:
                - MYSQL_ROOT_PASSWORD=UKhzlwBPl9882zEs
        restart: always
    myadmin:
            image: phpmyadmin/phpmyadmin
            ports:
                    - 8080:80
            volumes:
                    - /etc/timezone:/etc/timezone:ro
                    - /etc/localtime:/etc/localtime:ro
            links:
                    - db:db
            restart: always
